SELECT COALESCE(M.AUTOR, 'SEM_AUTOR') AUTOR, A.IDENTIFICACAO, M.TITULO_MATERIAL, M.ID CODIGO_MATERIAL, M.EDITORA
FROM LCL.V_MATERIAL M
     LEFT JOIN LCL.AUTOR A ON A.ID = M.ID_AUTOR
WHERE TIPO_MATERIAL <> 'PERIODICOS' AND
      COALESCE(A.NOME, '') LIKE '%'
ORDER BY M.AUTOR, TITULO_MATERIAL


-- SELECT * FROM LCL.AUTOR

-- SELECT * FROM LCL.MATERIAL_GERAL

-- SELECT * FROM LCL.MATERIAL_MIDIA_DIGITAL WHERE ID = 

-- SELECT * FROM LCL.V_MATERIAL WHERE ID = 

-- PRINCIPAL = 1 
-- IDENTAUTOR 
-- COD.MATERIAL = ID DO MATERIAL