SELECT M.AUTOR, M.TITULO_MATERIAL, E.UNIDADE, COUNT(1) AS TOTAL
FROM LCL.V_MATERIAL M
     INNER JOIN LCL.V_SGCI_EXEMPLAR E ON
                E.ID_MATERIAL = M.ID
WHERE E.UNIDADE LIKE '%' AND
      M.AUTOR LIKE '%'
GROUP BY M.AUTOR, M.TITULO_MATERIAL, E.UNIDADE
ORDER BY M.AUTOR, M.TITULO_MATERIAL, E.UNIDADE