SELECT U.ID ID_USUARIO,
       U.NOME,
       U.MATRICULA,
       E.CODIGO_BARRA,
       M.TITULO_MATERIAL,
       I.DATA_DEVOLUCAO,
       E.UNIDADE FILIAL_EXEMPLAR,
       U.FILIAL FILIAL_USUARIO
FROM LCL.USUARIO U
     INNER JOIN LCL.V_EMPRESTIMO I ON
                I.ID_USUARIO = U.ID
     INNER JOIN LCL.V_SGCI_EXEMPLAR E ON
                E.ID = I.ID_EXEMPLAR
     INNER JOIN LCL.V_MATERIAL M ON
                E.ID_MATERIAL = M.ID
WHERE U.FILIAL LIKE '%' AND
      I.DATA_DEVOLUCAO < '2024-11-28' AND
      DATEPART(YEAR, I.DATA_DEVOLUCAO) = '2024' AND
      I.DEVOLUCAO_DATA_HORA IS NULL AND
      U.NOME LIKE '%' AND
      U.ID_CATEGORIA LIKE '%'
ORDER BY FILIAL_USUARIO, U.NOME, I.DATA_HORA