SELECT E.CODIGO_BARRA,
       E.UNIDADE,
       COALESCE(NULLIF (M.TITULO_MATERIAL, ''), 'MATERIAL SEM TÍTULO REGISTRADO') TITULO 
FROM LCL.V_SGCI_EXEMPLAR E
     INNER JOIN LCL.V_MATERIAL M ON
                M.ID = E.ID_MATERIAL
WHERE COALESCE(M.AUTOR, '') = '' AND
      M.TIPO_MATERIAL = 'BOOKS'
ORDER BY M.AUTOR, E.TITULO