SELECT M.TITULO_MATERIAL, M.TIPO_MATERIAL, COUNT (*) VEZES_EMPRESTADAS 
FROM LCL.V_EMPRESTIMO I
     INNER JOIN LCL.EXEMPLAR E ON
                E.ID = I.ID_EXEMPLAR
     INNER JOIN LCL.V_MATERIAL M ON
                M.ID = E.ID_MATERIAL
WHERE I.DATA_HORA >= '01/01/2020' AND
      I.DATA_HORA <= '02/12/2024' AND
      M.ID_TIPO_MATERIAL LIKE '%'
GROUP BY M.TITULO_MATERIAL, M.TIPO_MATERIAL 
HAVING  COUNT (*) > 5
ORDER BY M.TIPO_MATERIAL, VEZES_EMPRESTADAS DESC