SELECT E.CODIGO_BARRA,
       M.TITULO_MATERIAL,
       COALESCE(M.AUTOR, 'SEM AUTOR REGISTRADO') AUTOR,
       O.APELIDO,
       UORIGEM.SIGLA UNIDADE_ORIGEM,
       T.DATA_HORA_ORIGEM,
       UDESTINO.SIGLA UNIDADE_DESTINO
FROM LCL.TRANSITO T
     INNER JOIN LCL.EXEMPLAR E ON
                E.ID = T.ID_EXEMPLAR
     INNER JOIN LCL.V_MATERIAL M ON
                M.ID = E.ID_MATERIAL
     INNER JOIN ACS.V_OPERADOR O ON
                O.ID = T.ID_ACESSO_ORIGEM
     INNER JOIN LCL.UNIDADE UORIGEM ON
                UORIGEM.ID = T.ID_UNIDADE_ORIGEM
     INNER JOIN LCL.UNIDADE UDESTINO ON
                UDESTINO.ID = T.ID_UNIDADE_DESTINO
WHERE T.DATA_HORA_RECEBIMENTO IS NULL
ORDER BY UNIDADE_ORIGEM, T.DATA_HORA_ORIGEM