SELECT COALESCE(M.AUTOR, 'SEM_AUTOR') AUTOR, A.IDENTIFICACAO, M.TITULO_MATERIAL, M.ID CODIGO_MATERIAL, M.EDITORA
FROM LCL.V_MATERIAL M
     LEFT JOIN LCL.AUTOR A ON A.ID = M.ID_AUTOR
WHERE TIPO_MATERIAL <> 'PERIODICOS' AND
      COALESCE(A.NOME, '') LIKE '%'
ORDER BY M.AUTOR, TITULO_MATERIAL