SELECT P.PALAVRA_CHAVE, COUNT(*) QUANTIDADE
FROM LCL.PALAVRA_CHAVE P
     INNER JOIN LCL.MATERIAL_X_PALAVRA_CHAVE M ON
                M.ID_PALAVRA_CHAVE = P.ID
WHERE P.PALAVRA_CHAVE LIKE '%'
GROUP BY P.PALAVRA_CHAVE
ORDER BY P.PALAVRA_CHAVE