SELECT U.ID ID_USUARIO,
    U.NOME,
    U.MATRICULA,
    E.CODIGO_BARRA,
    M.TITULO_MATERIAL,
    I.DATA_DEVOLUCAO,
    E.UNIDADE FILIAL_EXEMPLAR,
    U.FILIAL FILIAL_USUARIO
FROM LCL.V_EMPRESTIMO I
    INNER JOIN LCL.USUARIO U ON
               U.ID = I.ID_USUARIO 
    INNER JOIN LCL.V_SGCI_EXEMPLAR E ON
               E.ID = I.ID_EXEMPLAR
    INNER JOIN LCL.V_MATERIAL M ON
               M.ID = E.ID_MATERIAL
WHERE U.FILIAL LIKE '%' AND
      I.DATA_DEVOLUCAO < '2024-11-28' AND
      DATEPART(YEAR, I.DATA_DEVOLUCAO) = '2024' AND
      I.DEVOLUCAO_DATA_HORA IS NULL AND
      U.NOME LIKE '%' AND
      U.ID_CATEGORIA LIKE '%'
ORDER BY FILIAL_USUARIO, U.NOME, I.DATA_HORA