SELECT B.BAIXA,
       U.SIGLA,
       I.RECEBIMENTO_DATA_HORA DATA_RECEBIMENTO_MULTA,
       I.DEVOLUCAO_DATA_HORA DATA_DEVOLUCAO_DO_EXEMPLAR,
       L.NOME,
       E.CODIGO_BARRA,
       I.MULTA_VALOR,
       I.MULTA_DESCONTO,
       COALESCE(I.MULTA_OBSERVACAO, '-') MULTA_OBSERVACAO,
       O.APELIDO
FROM LCL.EXEMPLAR E
     INNER JOIN LCL.V_EMPRESTIMO I ON
                I.ID_EXEMPLAR = E.ID
     INNER JOIN LCL.MULTA M ON
                M.ID = I.MULTA_ID
     INNER JOIN LCL.BAIXA_MULTA B ON
                B.ID = I.RECEBIMENTO_ID_BAIXA_MULTA
     INNER JOIN LCL.UNIDADE U ON
                U.ID = E.ID_UNIDADE
     INNER JOIN LCL.USUARIO L ON
                L.ID = I.ID_USUARIO
     INNER JOIN LCL.RECEBIMENTO R ON
                R.ID = M.ID_RECEBIMENTO
     INNER JOIN ACS.V_OPERADOR O ON
                O.ID = R.ID_ACESSO
WHERE U.SIGLA LIKE '%' AND
      I.RECEBIMENTO_DATA_HORA BETWEEN '01/01/2024' AND '01/01/2025' AND
      O.APELIDO LIKE '%' AND
      L.NOME LIKE '%' AND
      B.BAIXA NOT IN ('MULTA INDEVIDA','ABONO')
ORDER BY U.SIGLA, B.BAIXA, I.RECEBIMENTO_DATA_HORA, L.NOME