SELECT U.FILIAL FILIAL, E.CODIGO_BARRA, M.TITULO_MATERIAL, U.ID, U.NOME, U.MATRICULA, U.ID_CATEGORIA, V.DATA_DEVOLUCAO
FROM LCL.V_EMPRESTIMO V
     INNER JOIN LCL.USUARIO U ON
                U.ID = V.ID_USUARIO
     INNER JOIN LCL.EXEMPLAR E ON
                E.ID = V.ID_EXEMPLAR
     INNER JOIN LCL.V_MATERIAL M ON
                M.ID = E.ID_MATERIAL
WHERE U.FILIAL LIKE '%' AND
      V.ESTADO IN ('EMPRESTADO', 'ATRASADO') AND
      V.DATA_DEVOLUCAO BETWEEN '2024-01-01' AND '2024-11-25' AND
      U.ID_CATEGORIA LIKE '%'
ORDER BY FILIAL, DATA_DEVOLUCAO, NOME