ALTER FUNCTION REL.F_046( @CHAVE_PESQUISA VARCHAR(256) )
RETURNS @RETORNO TABLE( PALAVRA_CHAVE VARCHAR(256),
                        QUANTIDADE INT ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT P.PALAVRA_CHAVE, COUNT(*) QUANTIDADE
  FROM LCL.PALAVRA_CHAVE P WITH(NOLOCK)
       INNER JOIN LCL.MATERIAL_X_PALAVRA_CHAVE M WITH(NOLOCK) ON
                  M.ID_PALAVRA_CHAVE = P.ID
  WHERE P.PALAVRA_CHAVE LIKE '%' + @CHAVE_PESQUISA + '%'
  GROUP BY P.PALAVRA_CHAVE
  
  RETURN

END