ALTER FUNCTION REL.F_034()
RETURNS @RETORNO TABLE( SIGLA VARCHAR(16),
                        TOTAL_DE_EXEMPLARES INT,
                        EXEMPLARES_BAIXADOS INT,
                        EXEMPLARES_ATIVOS INT ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT U.SIGLA,
         COUNT(ID_UNIDADE) TOTAL_DE_EXEMPLARES,
         SUM(CASE WHEN E.ESTADO = 'BAIXADO' THEN 1 ELSE 0 END) EXEMPLARES_BAIXADOS,
         SUM(CASE WHEN E.ESTADO <> 'BAIXADO' THEN 1 ELSE 0 END) EXEMPLARES_ATIVOS
  FROM LCL.EXEMPLAR E WITH(NOLOCK)
       INNER JOIN LCL.UNIDADE U WITH(NOLOCK) ON
                  U.ID = E.ID_UNIDADE
  GROUP BY U.SIGLA

  RETURN

END