ALTER FUNCTION REL.F_032()
RETURNS @RETORNO TABLE( TITULO VARCHAR(256) ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT M.TITULO
  FROM LCL.V_MATERIAL_GERAL M
  WHERE COALESCE(CDD, '') =  '' AND
        ID_TIPO_MATERIAL = 1

  RETURN

END