ALTER FUNCTION REL.F_042( @DATA_INICIAL DATE,
                          @DATA_FINAL DATE,
                          @TIPO_MATERIAL VARCHAR(128) )
RETURNS @RETORNO TABLE( TITULO_MATERIAL VARCHAR(256),
                        TIPO_MATERIAL VARCHAR(128),
                        VEZES_EMPRESTADAS INT ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT M.TITULO_MATERIAL, M.TIPO_MATERIAL, COUNT (*) VEZES_EMPRESTADAS 
  FROM LCL.V_EMPRESTIMO I
       INNER JOIN LCL.EXEMPLAR E WITH(NOLOCK) ON
                  E.ID = I.ID_EXEMPLAR
       INNER JOIN LCL.V_MATERIAL M ON
                  M.ID = E.ID_MATERIAL
  WHERE I.DATA_HORA >= @DATA_INICIAL AND
        I.DATA_HORA <= @DATA_FINAL AND
        M.ID_TIPO_MATERIAL LIKE '%' + @TIPO_MATERIAL + '%'
  GROUP BY M.TITULO_MATERIAL, M.TIPO_MATERIAL 
  HAVING  COUNT (*) > 5
  
  RETURN

END