ALTER FUNCTION REL.F_045( @AUTOR VARCHAR(256) )
RETURNS @RETORNO TABLE( AUTOR VARCHAR(256),
                        IDENTIFICACAO VARCHAR(16),
                        TITULO_MATERIAL VARCHAR(256),
                        CODIGO_MATERIAL BIGINT,
                        EDITORA VARCHAR(128) ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT COALESCE(M.AUTOR, 'SEM_AUTOR') AUTOR,
         A.IDENTIFICACAO,
         M.TITULO_MATERIAL,
         M.ID CODIGO_MATERIAL,
         M.EDITORA
  FROM LCL.V_MATERIAL M
       LEFT JOIN LCL.AUTOR A WITH(NOLOCK) ON
                 A.ID = M.ID_AUTOR
  WHERE TIPO_MATERIAL <> 'PERIODICOS' AND
        COALESCE(A.NOME, '') LIKE '%' + @AUTOR + '%'
  
  RETURN

END