ALTER FUNCTION REL.F_043( @FILIAL VARCHAR(16),
                          @AUTOR VARCHAR(256) )
RETURNS @RETORNO TABLE( AUTOR VARCHAR(256),
                        TITULO_MATERIAL VARCHAR(256),
                        UNIDADE VARCHAR(16),
                        TOTAL INT ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT M.AUTOR, M.TITULO_MATERIAL, E.UNIDADE, COUNT(1) AS TOTAL
  FROM LCL.V_MATERIAL M
       INNER JOIN LCL.V_SGCI_EXEMPLAR E ON
                  E.ID_MATERIAL = M.ID
  WHERE E.UNIDADE LIKE @FILIAL AND
        M.AUTOR LIKE @AUTOR
  GROUP BY M.AUTOR, M.TITULO_MATERIAL, E.UNIDADE

  RETURN

END