ALTER FUNCTION REL.F_047( @FILIAL VARCHAR(18),
                          @DATA_INICIAL DATETIME2,
                          @DATA_FINAL DATETIME2 )
RETURNS @RETORNO TABLE( UNIDADE VARCHAR(16),
                        MOTIVO_BAIXA VARCHAR(32),
                        TITULO_MATERIAL VARCHAR(256),
                        AUTOR VARCHAR(256),
                        DATA_HORA_BAIXA DATETIME2,
                        ID_MATERIAL BIGINT,
                        EXEMPLAR BIGINT) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT V.UNIDADE,
         B.BAIXA MOTIVO_BAIXA,
         COALESCE(NULLIF(M.TITULO_MATERIAL, ''), 'SEM TITULO REGISTRADO') TITULO_MATERIAL,
         COALESCE (A.NOME, 'SEM AUTOR REGISTRADO') AUTOR,
         E.DATA_HORA_BAIXA,
         M.ID ID_MATERIAL,
         E.CODIGO_BARRA EXEMPLAR
  FROM LCL.EXEMPLAR E
       LEFT JOIN LCL.V_SGCI_EXEMPLAR V ON
                 V.ID = E.ID
       LEFT JOIN LCL.BAIXA_EXEMPLAR B ON
                 B.ID = E.ID_BAIXA_EXEMPLAR
       LEFT JOIN LCL.V_MATERIAL M ON
                 M.ID = E.ID_MATERIAL
       LEFT JOIN LCL.AUTOR A ON
                 A.ID = M.ID_AUTOR
  WHERE B.BAIXA IS NOT NULL AND
        V.UNIDADE LIKE '%' + @FILIAL + '%' AND
        E.DATA_HORA_BAIXA BETWEEN @DATA_INICIAL AND @DATA_FINAL
  
  RETURN

END