ALTER FUNCTION REL.F_040( @FILIAL VARCHAR(8),
                          @DATA_INICIAL DATETIME2,
                          @DATA_FINAL DATETIME2,
                          @OPERADOR VARCHAR(256),
                          @USUARIO VARCHAR(256) )
RETURNS @RETORNO TABLE( BAIXA VARCHAR(32),
                        SIGLA VARCHAR(16),
                        DATA_RECEBIMENTO_MULTA DATETIME2,
                        DATA_DEVOLUCAO_DO_EXEMPLAR DATETIME2,
                        NOME VARCHAR(256),
                        CODIGO_BARRA BIGINT,
                        MULTA_VALOR NUMERIC(19,2),
                        MULTA_DESCONTO NUMERIC(19,2),
                        MULTA_OBSERVACAO VARCHAR(MAX),
                        APELIDO VARCHAR(128) ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT B.BAIXA,
         U.SIGLA,
         I.RECEBIMENTO_DATA_HORA DATA_RECEBIMENTO_MULTA,
         I.DEVOLUCAO_DATA_HORA DATA_DEVOLUCAO_DO_EXEMPLAR,
         L.NOME,
         E.CODIGO_BARRA,
         I.MULTA_VALOR,
         I.MULTA_DESCONTO,
         COALESCE(I.MULTA_OBSERVACAO, '-') MULTA_OBSERVACAO,
         O.APELIDO
  FROM LCL.EXEMPLAR E WITH(NOLOCK)
       INNER JOIN LCL.V_EMPRESTIMO I ON
                  I.ID_EXEMPLAR = E.ID
       INNER JOIN LCL.MULTA M WITH(NOLOCK) ON
                  M.ID = I.MULTA_ID
       INNER JOIN LCL.BAIXA_MULTA B WITH(NOLOCK) ON
                  B.ID = I.RECEBIMENTO_ID_BAIXA_MULTA
       INNER JOIN LCL.UNIDADE U WITH(NOLOCK) ON
                  U.ID = E.ID_UNIDADE
       INNER JOIN LCL.USUARIO L WITH(NOLOCK) ON
                  L.ID = I.ID_USUARIO
       INNER JOIN LCL.RECEBIMENTO R WITH(NOLOCK) ON
                  R.ID = M.ID_RECEBIMENTO
       INNER JOIN ACS.V_OPERADOR O ON
                  O.ID = R.ID_ACESSO
  WHERE U.SIGLA LIKE '%' + @FILIAL + '%' AND
        I.RECEBIMENTO_DATA_HORA BETWEEN @DATA_INICIAL AND @DATA_FINAL AND
        O.APELIDO LIKE '%' + @OPERADOR + '%' AND
        L.NOME LIKE '%' + @USUARIO + '%' AND
        B.BAIXA NOT IN ('MULTA INDEVIDA','ABONO')
  
  RETURN

END