ALTER FUNCTION REL.F_037( @FILIAL VARCHAR(16),
                          @CDD_INICIAL VARCHAR(32),
                          @CDD_FINAL VARCHAR(32) )
RETURNS @RETORNO TABLE( UNIDADE VARCHAR(16),
                        CDD VARCHAR(32),
                        TITULO_MATERIAL VARCHAR(256),
                        AUTOR VARCHAR(256),
                        EXEMPLAR BIGINT ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT E.UNIDADE, M.CDD, V.TITULO_MATERIAL, V.AUTOR, E.ID EXEMPLAR
  FROM LCL.V_SGCI_EXEMPLAR E
       INNER JOIN LCL.V_MATERIAL_GERAL M ON
                  M.ID = E.ID_MATERIAL
       INNER JOIN LCL.V_MATERIAL V ON
                  V.ID = M.ID
       INNER JOIN LCL.AUTOR A WITH(NOLOCK) ON
                  A.ID = V.ID_AUTOR
  WHERE E.UNIDADE LIKE '%' + @FILIAL + '%' AND
        M.CDD BETWEEN @CDD_INICIAL AND @CDD_FINAL AND
        E.DATA_HORA_BAIXA IS NULL

  RETURN

END