ALTER FUNCTION REL.F_035()
RETURNS @RETORNO TABLE( CODIGO_BARRA BIGINT,
                        UNIDADE VARCHAR(16),
                        TITULO VARCHAR(256) ) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT E.CODIGO_BARRA,
         E.UNIDADE,
         COALESCE(NULLIF (M.TITULO_MATERIAL, ''), 'MATERIAL SEM TITULO REGISTRADO') TITULO 
  FROM LCL.V_SGCI_EXEMPLAR E
       INNER JOIN LCL.V_MATERIAL M ON
                  M.ID = E.ID_MATERIAL
  WHERE COALESCE(M.AUTOR, '') = '' AND
        M.TIPO_MATERIAL = 'BOOKS'

  RETURN

END