ALTER FUNCTION REL.F_038( @FILIAL VARCHAR(16),
                           @DATA_DEVOLUCAO_INI DATE,
                           @DATA_DEVOLUCAO_FIM DATE,
                           @CATEGORIA BIGINT )
RETURNS @RETORNO TABLE( FILIAL VARCHAR(16),
                        CODIGO_BARRA BIGINT,
                        TITULO_MATERIAL VARCHAR(256),
                        ID BIGINT,
                        NOME VARCHAR(256),
                        MATRICULA VARCHAR(16),
                        ID_CATEGORIA BIGINT,
                        DATA_DEVOLUCAO DATE) AS
BEGIN

  INSERT INTO @RETORNO
  SELECT U.FILIAL FILIAL, E.CODIGO_BARRA, M.TITULO_MATERIAL, U.ID, U.NOME, U.MATRICULA, U.ID_CATEGORIA, V.DATA_DEVOLUCAO
  FROM LCL.V_EMPRESTIMO V
       INNER JOIN LCL.USUARIO U ON
                  U.ID = V.ID_USUARIO
       INNER JOIN LCL.EXEMPLAR E ON
                  E.ID = V.ID_EXEMPLAR
       INNER JOIN LCL.V_MATERIAL M ON
                  M.ID = E.ID_MATERIAL
  WHERE U.FILIAL LIKE @FILIAL AND
        V.ESTADO IN ('EMPRESTADO', 'ATRASADO') AND
        V.DATA_DEVOLUCAO BETWEEN @DATA_DEVOLUCAO_INI AND @DATA_DEVOLUCAO_FIM AND
        U.ID_CATEGORIA LIKE @CATEGORIA
  
  RETURN

END